services:
  longhabit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: longhabit
    restart: unless-stopped
    environment:
      - MAILER_CRON_SCHEDULE=${MAILER_CRON_SCHEDULE:-0 9 * * *}
    ports:
      - '8090:8090'
    volumes:
      - ./db:/app/db
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      start_period: 5s
      interval: 30s
      timeout: 30s
      retries: 3
