services:
  longhabit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: longhabit
    restart: unless-stopped
    environment:
      - MAILER_CRON_SCHEDULE=${MAILER_CRON_SCHEDULE:-0 9 * * *}
      - VITE_BACKEND_URL=/api
    ports:
      - '8090:8090'
    volumes:
      - ./db:/app/db
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
